# Generated by Django 4.1.12 on 2024-04-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_public_Date',
            field=models.CharField(default=111, max_length=255),
            preserve_default=False,
        ),
    ]
