# Generated by Django 4.1.12 on 2024-04-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_article_public_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
    ]
