# Generated by Django 4.1.12 on 2024-04-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_article_rating_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_article_rating_tb',
            name='article_publicate_Date',
        ),
        migrations.AddField(
            model_name='user_article_rating_tb',
            name='article_public_Date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
