# Generated by Django 4.1.12 on 2024-04-30 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_user_article_rating_tb_article_publicate_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Article_TB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('abstract', models.TextField()),
                ('content_url', models.URLField()),
                ('article_public_Date', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
