# Generated by Django 4.1.12 on 2024-05-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_age_recommand_article_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_Article_TB',
        ),
    ]
