# Generated by Django 4.1.12 on 2024-05-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_users_info_user_age_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('signup_purpose', models.CharField(max_length=255)),
                ('article_category', models.CharField(max_length=50)),
                ('click_day', models.CharField(max_length=10)),
                ('click_time', models.CharField(max_length=10)),
                ('click_date', models.DateTimeField()),
            ],
        ),
    ]
