# Generated by Django 4.1.12 on 2024-05-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_logmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogModel',
        ),
    ]
